### ISSUE TITLE
How to use... doc link

### ISSUE THREAD

**Issue by siliconhippy** [matthuisman/kodi.proxy#10]
I couldn't find any info.

1. Is this a replacement for Kodi Settings > System > Internet > Proxy (client)?
Or a proxy server where you can/cannot set individual user/password proxy accounts?
3. I tried to instal the kodi.proxy-master.zip on my AlexElec 20.1 Kodi TV box, but it gives me " install failed..."
4. How do I use this ? Not a dev, but will the service start be something like enable/start/status/disable:
 #systemctl enable ./proxy.py "plugin://script.module.slyguy" service
5. What are use cases? I am looking at the Kodi native proxy client and wondering if besides tvheadend, other Kodi apps/PVRs can be individually passed through a proxy server (that I set up) with assigning individual user/passwords to users
6. What is a good, simple http(s) proxy server for item5 to set up in a VPS? Squid?

**Comment by matthuisman** [comment]
no - this is not a proxy in those terms. 
This is a proxy for kodi itself.

This is not suitable for your use case

**Comment by matthuisman** [comment]
"A basic Kodi "emulator" to allow non-kodi programs to obtain playable urls from the various Slyguy addons. 
Commonly used with TvHeadend"
