### ISSUE TITLE
Channel 7 over proxy

### ISSUE THREAD

**Issue by skaface** [matthuisman/kodi.proxy#11]
Hi, I am trying to view channel 7 australia directly with ffmpeg (i'm actually trying to set up tvheadend with iptv channels). The only way I can successfully stream channel 7 is using your plugin directly inside Kodi, any other method I try, I am receiving a 403 forbidden error when it tries to download the encryption key. Is there anything special that kodi is doing? I have tried using the url provided by your proxy software installed locally as well as your public link, setting the user agent and other headers that are shown in your playlists.

ffmpeg -probesize 10M -analyzeduration 0 -fpsprobesize 0 -headers "referer: "$'\r\n'"seekable: 0"$'\r\n' -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" -i "https://i.mjh.nz/7-mel1.m3u8" -vcodec copy -acodec copy -metadata service_name=mjh-7-mel1 -v debug -f mpegts pipe:1

.............
[tcp @ 0x562d45eb4d40] Successfully connected to 23.55.38.90 port 443
[https @ 0x562d45eb1440] request: GET /hls/live/MEL1/000013ce-0011-0c2f-170e-0000928aeb11_0_1687938777.key?hdnts=exp=1688022316~acl=/*~hmac=0638767ea903b9b535f7135bd31a1c63968309634ad3efa5fd3dcd9c94a8b15a&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY4ODAyMjMxNn0sIkRhdGVHcmVhdGVyVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg3OTM1OTE1fX19XX0_&Signature=jOrv6VFIYInK5wfnVZsDwTKB~39XMUEKHzLZHNmBUcdZBcPeB03y1Sg02GPCe1ontHD4ATkDmNdjg38BYPU21voCauld-k7TLALgmUvY90vYLGLGYWpllwcVln7P03y6KdyTeoImRg2g-UM3k4pahYIVjcxSLpZdwsNI6588gOK5mW3qiqdcJw-AfPYe1ICgObOSlPmITh3ZbrvL9uDfUM63h-2TP2n3I6dueC2IniVCwzp1S3EpkzHYi-qnq5xx6WmZmW-KZfWhGSPZLtzFuKevSZL~bvX3aJkituIYJG2CxHFmE1d1AOtZqkLe1zIl5usrhOqAxGSCdAI223Iu1A__&Key-Pair-Id=APKAIOT4M6KN6CQOAWEQ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Accept: */*
Range: bytes=0-
Connection: keep-alive
Host: npc-live-sevennetwork.akamaized.net
Icy-MetaData: 1
referer: 
seekable: 0

[https @ 0x562d45eb1440] HTTP error 403 Forbidden

**Comment by matthuisman** [comment]
have you tried this playlist that I specifically generate for tvheadend?

https://i.mjh.nz/au/Melbourne/tvh-tv.m3u8
