### ISSUE TITLE
Sling Integration Question (subtitles/quality)

### ISSUE THREAD

**Issue by xags** [matthuisman/kodi.proxy#12]
Hello,

Could this code be utilized for a different add-on (SlingTV addon) to better handle/forcing subtitles and quality settings? I see that a majority of your plugins utilize the script.modules.slyguy addon that looks to handle parsing the dash stream and doing things like allowing subtitles to work properly within Kodi--specifically the 'def _parse_dash(self, response)' function.

**Comment by matthuisman** [comment]
that addon would need to be rewritten to use my framework. big job
