### ISSUE TITLE
Issue with tv_grab_iptv_merge

### ISSUE THREAD

**Issue by stuckinthe** [matthuisman/kodi.proxy#17]
I am unable to get the tv_grab_iptv_merge to merge the guide data properly. I have setup kodi using the docker and I tried by using the shell. It looks like tv_grab_iptv_merge is not reading in the files to be parsed as I get an merged file with just  <?xml version="1.0" encoding="UTF-8"?><tv></tv>.  

I am using file paths when I setup IPTV Merge through the shell so /home/kodi/stream.xml and /home/stream/stream2.xml

I also tried iptv_merge.m3u8.sh and it gives me an empty playlist error.

Looks like an issue with the data being read into the addons/plugin.program.iptv.merge/resources/lib/iptv_manager.py from kodi.proxy

or maybe I am doing something wrong.

**Comment by stuckinthe** [comment]
I ran in debug mode and there is an issue when creating the tmp file

No such file or directory: '/home/kodi/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp'

**Comment by matthuisman** [comment]
ignore the android thing. pretty sure the proxy just sets its os to android. shouldnt matter.
there should have been an exception traceback after DEBUG - plugin.program.iptv.merge - Failed to detect file type

**Comment by stuckinthe** [comment]
ERROR - plugin.program.iptv.merge - [Errno 2] No such file or directory: '/home/kodi/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp'
Traceback (most recent call last):
  File "/home/kodi/kodi.proxy/addons/plugin.program.iptv.merge/resources/lib/merger.py", line 234, in _process_path
    with open(file_path, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^

The file needed isn't being written.

**Comment by matthuisman** [comment]
odd. as the line /home/kodi/kodi.proxy/addon_data/plugin.program.iptv.merge/trial.xml > /home/kodi/kodi.proxy/addon_data/plugin.program.iptv.merge/iptv_merge_tmp is logged after it copies


Does /home/kodi/kodi.proxy/addon_data/plugin.program.iptv.merge/trial.xml exist?

**Comment by stuckinthe** [comment]
Yes the file exists. I had the file outside of the kodi.proxy env path so I moved it to the above directory but that didn't solve the issue. I just tried with a smaller file to see if that could have been an issue but I still get the same error. It starts to copy the iptv_merge_tmp file and then just quits.

**Comment by matthuisman** [comment]
permissions?

**Comment by stuckinthe** [comment]
I'm running python as the same user as the directories. I tailed the plugin.program.iptv.merge and it starts to create the iptv_merge_tmp and stops.

**Comment by stuckinthe** [comment]
I just did a fresh install using Ubuntu on a VirtualBox and I ran into the same issue. When I try to run a merge through the CLI by selecting the number, it says that it's already doing a merge all the time. I also noticed that it always gives me the option to setup simple iptv even after I complete the task. It also says this in the app on kodi but it doesn't cause any issues. My guess is that when I try to do an epg merge by using the tv_script_merge bash script somewhere it is checking for a merge and reports that one is in process and stops the bash script.

I would prefer to do it with kodi.proxy as I can check for a video being played before I do a merge.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/kodi.proxy/commit/6c4899d446a2a540b318f76f0c82f7c1bce173a3 should fix the merge issue :) so simple! haha. the xbmcvfs.copy wasnt implemented so it was essentially not copying something when it should have been

As for the "setup itptv simple". dont worry about that. itll fail as the iptv simple addon cant be found / installed

**Comment by matthuisman** [comment]
i also just did an update to proxy and IPTV merge addon so
1) setup now "works" and stops showing
2) The run merge in the addon menu also now works

youll need to pull latest proxy code and also update the merge addon
