### ISSUE TITLE
is there a way to use other kodi plugins

### ISSUE THREAD

**Issue by wjcarpenter** [matthuisman/kodi.proxy#18]
Is there a way to have the proxy use other kodi plugins? In particular, 3 of the 4 test videos need inputstream.adaptive. Is there a way to have it load plugins like that so it can play those test videos?

**Comment by matthuisman** [comment]
Widevine won't work via proxy.

**Comment by wjcarpenter** [comment]
Does that mean it can't be done or that it just isn't implemented? (I don't know much about how widevine works).

**Comment by matthuisman** [comment]
Can't be done
