### ISSUE TITLE
Inputstream Adaptive version in Docker

### ISSUE THREAD

**Issue by nickp27** [matthuisman/kodi.proxy#3]
I am running kodi.proxy in Docker on Unraid. When I try to run any of the plugins which require Inputstream (Optus Sport), it gives an error:

Optus Sport - Error
Content requires a newer version of Inputstream Adaptive
Minimum required version: 2.2.27
Your current version: 2.0.0 [OK]

I have tried forcing it to install Inputstream Adaptive Testing, but this doesn't seem to do anything. 

I suspect it might be to do worth the coding/version criteria in script.module.slyguy>resources>modules>slyguy>inputstream.py not reacting well to being in a docker environment, but wondered if there might be a more straightforward answer.

**Comment by matthuisman** [comment]
its not possible to run Inputstream Adaptive via it and never will be. 
IA is a BINARY add-on. Big difference.
