### ISSUE TITLE
Kayo Sports plugin no longer working

### ISSUE THREAD

**Issue by speedst3r** [matthuisman/kodi.proxy#4]
I was previously using the Kayo Sports plugin with kodi.proxy in a Docker container with no issue. I'm unsure when it stopped working, but it seems no stream data is received.

tvheadend logs at:
https://pastebin.com/6z84L9Zz

I'm using latest tvheadend and built tvh-proxy after a pull of this repo. I also cleared the mounted config volume so it was configured again from scratch. After starting the container, followed the instructions in docker/README.md to configure IPTV Merge and Kayo plugins.

**Comment by speedst3r** [comment]
Added debug options to ffmpeg in tvh.sh:
https://pastebin.com/RCJGteLd

**Comment by matthuisman** [comment]
should be fixed with latest commit: https://github.com/matthuisman/kodi.proxy/commit/6a87ef6bce3199cdc63ffdadfd8871af190ae773

**Comment by speedst3r** [comment]
Confirmed, rebuilt the container with the latest commit and was able to setup channels again - thanks!
