### ISSUE TITLE
Kayo EPG not populating

### ISSUE THREAD

**Issue by speedst3r** [matthuisman/kodi.proxy#5]
For several weeks now the Kayo EPG is populated by 90 minute blocks with "No listing available". I have reinstalled the Kayo and IPTV Merge plugins (purging their data) and it does not seem to have made a difference.

I notice IPTV Merge has no EPG option for Kayo anymore (should happen automatically?), but the EPG is not being populated.

![image](https://user-images.githubusercontent.com/2178183/148718103-121c6e68-90f1-4ecd-bed6-b1272fd6b184.png)

**Comment by matthuisman** [comment]
Oh. Your not using Kodi.....
Ummm maybe try update IPTV Merge via Kodi.proxy
All my content relies on everything being upto date

**Comment by speedst3r** [comment]
> Oh. Your not using Kodi.....

No, tvheadend with HDHR patch so I can tune from Plex (the tuning part works great, just no EPG)

> Ummm maybe try update IPTV Merge via Kodi.proxy All my content relies on everything being upto date

All add-ons are up to date, unless there are newer versions that don't seem to be downloading?

```
root@tvheadend-7d4dfcfbcf-z59gt:/config# /usr/share/kodi.proxy/proxy "update://all"

slyguy.dependencies (0.0.1): Upto date
script.module.slyguy (0.49.2): Upto date
repository.slyguy (0.0.2): Upto date
plugin.program.iptv.merge (0.21.6): Upto date
plugin.video.kayo.sports (0.12.7): Upto date
```

**Comment by speedst3r** [comment]
I added a URL EPG (https://i.mjh.nz/Kayo/epg.xml) as there was no option to automatically use one from the add-on. That seems to have worked, but not sure that should be the right way?

**Comment by matthuisman** [comment]
Oh. You have added the epg url for proxy epg right? That is still required

**Comment by speedst3r** [comment]
I had it previously, but removed as I saw in IPTV Merge's SQLite DB that it had been deprecated and EPG was part of the add-on.

**Comment by matthuisman** [comment]
Oh. No you need that.
In IPTV merge itself, you no longer need to add Kayo as epg source. But in tvheadend you still need the iptv merge epg source.
