### ISSUE TITLE
[Request] Add Python 3 (Kodi 19+)

### ISSUE THREAD

**Issue by 89z** [matthuisman/kodi.proxy#6]
Does this work with Python 3? I get this message:

~~~
Traceback (most recent call last):
  File "D:\Desktop\kodi.proxy-master\proxy.py", line 12, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
~~~

https://github.com/matthuisman/kodi.proxy/blob/63e02a1864ceb76c366e3c70300eebfc6866d10b/proxy.py#L1-L12

**Comment by matthuisman** [comment]
Python2 only as it's emulating Kodi 18 which uses python2. I'll look at
doing a python3 eventually.

**Comment by 89z** [comment]
Did you add Python 3?

**Comment by matthuisman** [comment]
It is now Python3 only :)
