### ISSUE TITLE
Feature: Support slyguy proxy for quality forcing

### ISSUE THREAD

**Issue by lionsnob** [matthuisman/kodi.proxy#8]
Thanks for this Matt! I've used kodi.proxy to integrate ESPN3/ESPN+ into TVHeadend and dynamically generate guide data. I can only get videos to play at 29.97 FPS though, while in Kodi they will play at 59.94 FPS.

I've tried changing the add-on settings.json (default_quality) to:
{
    "_fresh": "false",
    "_userdata": "redacted",
    "alt_languages": "false",
    "bookmarks": "false",
    "chunksize": "4096",
    **"default_quality": "1",**
    "http_retries": "2",
    "http_timeout": "30",
    "kiosk": "false",
    "live_play_type": "1",
    "max_bandwidth": "7",
    "service_delay": "0",
    "show_live_scores": "false",
    "sport_whitelist": "",
    "use_ia_hls_live": "false",                                                                                                                                                              
    "use_ia_hls_vod": "false",                                                                                                                                                               
    "verify_ssl": "true"                                                                                                                                                                     
}

I've also tried passing default_quality as a parameter:
plugin://slyguy.espn/?_=play&_play=1&content_id=$CONTENT&_is_live=1&default_quality=1&_noresume=.pvr

but neither work.

Any suggestions?

**Comment by matthuisman** [comment]
youll need to see if you can do it in ffmpeg / tvheadend.
Quality control is a kodi only feature which is done inside my slyguy.common service proxy.py which sits between all kodi requests and the internet. That is what removes the other qualities from the manifest before it gets to kodi.

You could try getting the service running via kodi.proxy I guess and then route requests via it.
Would be possible.

**Comment by lionsnob** [comment]
Perfect! I’ll start at the ffmpeg command in tvh.sh then.

Thanks! Steve

**Comment by matthuisman** [comment]
to try getting my service proxy.py working,

proxy.py ""plugin://script.module.slyguy" "service"
should start it.

Then edit https://github.com/matthuisman/kodi.proxy/blob/master/proxy.py#L504 and set that to http://127.0.0.1:52103

i should really introduce out-of-the-box support for this.
So if the service is started above, it automatically populates that config.

I think 127.0.0.1 may need to be your network local ip address. Too tired to think now how tvheadend pipes the data
Actually, i think 127.0.0.1 is fine as it uses the local ffmpeg and tvheadend takes care of sharing that output over network

**Comment by lionsnob** [comment]
This worked perfectly. Thanks!

**Comment by matthuisman** [comment]
i just had a play and seems to work already out-of-the-box pretty well
If the service is started, it'll write the proxy_path setting and the next call to a plugin will use that in its url.

Juts made a few quick updates to make it work a bit better
1) The service will now clear it's proxy_path when stopping (eg. Ctrl-C)
2) Latest proxy.py uses default quality of best. This has no affect unless the service is running.
